version: '3'
services:
  dev-service:
    container_name: node-development-container
    build: .
    ports:
    - "80:3000"
    image: node-development-image
    volumes:
    - ./src:/home/node/src
    - ./gitfile:/home/node/.gitconfig
    - ./auth.sh:/home/node/auth
    - ./secrets:/home/node/.ssh
  git-service:
    container_name: git-development-container
    build: .
    image: git-development-image
    volumes:
    - .:/home/node