version: '3'
services:
  node-service:
    container_name: node-container
    build: .
    command: [".ssh/n-k2"]
    ports:
    - "80:3000"
    image: node-dev-env-img
    volumes:
    - ./src:/home/node/src
    - ./gitfile:/home/node/.gitconfig
    - ./auth.sh:/home/node/auth.sh
    - ./secrets:/home/node/.ssh
  git-service:
    container_name: git-container
    build: .
    command: ["secrets/n-k2", "cp gitfile .gitconfig"]
    image: node-dev-env-img
    volumes:
    - .:/home/node